import type { Category, SubCategory, Product, FrequentlyBoughtBundle } from "@/types";

// Helper to create placeholder image URLs
const img = (text: string, bg: string) =>
  `https://placehold.co/200x200/${bg}/white?text=${encodeURIComponent(text)}`;

export const MOCK_CATEGORIES: Category[] = [
  {
    id: "cat-1",
    shop_id: "default",
    name: "Atta, Rice & Dal",
    image: img("Atta", "e8a87c"),
    sort_order: 1,
    popularity_score: 95,
    sales_count: 1200,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "cat-2",
    shop_id: "default",
    name: "Dairy & Eggs",
    image: img("Dairy", "f4d03f"),
    sort_order: 2,
    popularity_score: 92,
    sales_count: 1100,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "cat-3",
    shop_id: "default",
    name: "Snacks & Namkeen",
    image: img("Snacks", "e74c3c"),
    sort_order: 3,
    popularity_score: 88,
    sales_count: 950,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "cat-4",
    shop_id: "default",
    name: "Vegetables & Fruits",
    image: img("Veg", "2ecc71"),
    sort_order: 4,
    popularity_score: 85,
    sales_count: 900,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "cat-5",
    shop_id: "default",
    name: "Beverages",
    image: img("Drinks", "3498db"),
    sort_order: 5,
    popularity_score: 78,
    sales_count: 800,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "cat-6",
    shop_id: "default",
    name: "Biscuits & Cakes",
    image: img("Biscuits", "d35400"),
    sort_order: 6,
    popularity_score: 75,
    sales_count: 750,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "cat-7",
    shop_id: "default",
    name: "Personal Care",
    image: img("Care", "9b59b6"),
    sort_order: 7,
    popularity_score: 65,
    sales_count: 600,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "cat-8",
    shop_id: "default",
    name: "Household",
    image: img("Home", "1abc9c"),
    sort_order: 8,
    popularity_score: 60,
    sales_count: 550,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "cat-9",
    shop_id: "default",
    name: "Baby Care",
    image: img("Baby", "e91e63"),
    sort_order: 9,
    popularity_score: 45,
    sales_count: 400,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "cat-10",
    shop_id: "default",
    name: "Health",
    image: img("Health", "00bcd4"),
    sort_order: 10,
    popularity_score: 40,
    sales_count: 350,
    is_active: true,
    created_at: "2024-01-01T00:00:00Z",
  },
];

export const MOCK_SUBCATEGORIES: SubCategory[] = [
  // Atta, Rice & Dal
  { id: "sub-1-1", category_id: "cat-1", name: "Atta", sort_order: 1 },
  { id: "sub-1-2", category_id: "cat-1", name: "Rice", sort_order: 2 },
  { id: "sub-1-3", category_id: "cat-1", name: "Dal", sort_order: 3 },
  { id: "sub-1-4", category_id: "cat-1", name: "Besan, Sooji & Maida", sort_order: 4 },
  { id: "sub-1-5", category_id: "cat-1", name: "Rajma, Chhole & Pulses", sort_order: 5 },
  { id: "sub-1-6", category_id: "cat-1", name: "Millet & Other Flours", sort_order: 6 },
  { id: "sub-1-7", category_id: "cat-1", name: "Organic", sort_order: 7 },
  { id: "sub-1-8", category_id: "cat-1", name: "Poha, Daliya & Grains", sort_order: 8 },
  // Dairy & Eggs
  { id: "sub-2-1", category_id: "cat-2", name: "Milk", sort_order: 1 },
  { id: "sub-2-2", category_id: "cat-2", name: "Curd", sort_order: 2 },
  { id: "sub-2-3", category_id: "cat-2", name: "Paneer", sort_order: 3 },
  { id: "sub-2-4", category_id: "cat-2", name: "Butter & Ghee", sort_order: 4 },
  { id: "sub-2-5", category_id: "cat-2", name: "Eggs", sort_order: 5 },
  { id: "sub-2-6", category_id: "cat-2", name: "Cheese", sort_order: 6 },
  // Snacks & Namkeen
  { id: "sub-3-1", category_id: "cat-3", name: "Chips", sort_order: 1 },
  { id: "sub-3-2", category_id: "cat-3", name: "Namkeen", sort_order: 2 },
  { id: "sub-3-3", category_id: "cat-3", name: "Biscuits", sort_order: 3 },
  { id: "sub-3-4", category_id: "cat-3", name: "Chocolates", sort_order: 4 },
  // Vegetables & Fruits
  { id: "sub-4-1", category_id: "cat-4", name: "Fresh Vegetables", sort_order: 1 },
  { id: "sub-4-2", category_id: "cat-4", name: "Fresh Fruits", sort_order: 2 },
  { id: "sub-4-3", category_id: "cat-4", name: "Exotic", sort_order: 3 },
  // Beverages
  { id: "sub-5-1", category_id: "cat-5", name: "Tea & Coffee", sort_order: 1 },
  { id: "sub-5-2", category_id: "cat-5", name: "Soft Drinks", sort_order: 2 },
  { id: "sub-5-3", category_id: "cat-5", name: "Juices", sort_order: 3 },
];

export const MOCK_PRODUCTS: Product[] = [
  // Atta
  {
    id: "p-1",
    shop_id: "default",
    category_id: "cat-1",
    subcategory_id: "sub-1-1",
    name: "Aashirvaad Select 100% MP Sharbati Atta",
    image: img("Aashirvaad", "d4ac0d"),
    type: "piece",
    unit_type: "pack",
    price: 13800,
    mrp: 15400,
    stock: 12,
    low_stock_threshold: 5,
    brand: "Aashirvaad",
    tags: "Bought Earlier,Offer",
    weight_grams: 2000,
    active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "p-2",
    shop_id: "default",
    category_id: "cat-1",
    subcategory_id: "sub-1-1",
    name: "Fortune Multigrain Atta",
    image: img("Fortune", "27ae60"),
    type: "piece",
    unit_type: "pack",
    price: 32400,
    mrp: 38600,
    stock: 8,
    low_stock_threshold: 5,
    brand: "Fortune",
    tags: "Offer,No Maida",
    weight_grams: 5000,
    active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "p-3",
    shop_id: "default",
    category_id: "cat-1",
    subcategory_id: "sub-1-1",
    name: "Aashirvaad Shudh Chakki Atta (0% Maida)",
    image: img("Aashirvaad", "c0392b"),
    type: "piece",
    unit_type: "pack",
    price: 23600,
    mrp: 26200,
    stock: 25,
    low_stock_threshold: 5,
    brand: "Aashirvaad",
    tags: "No Maida,Popular",
    weight_grams: 5000,
    active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "p-4",
    shop_id: "default",
    category_id: "cat-1",
    subcategory_id: "sub-1-1",
    name: "Aashirvaad Shudh Chakki Atta 10kg",
    image: img("Aashirvaad", "c0392b"),
    type: "piece",
    unit_type: "pack",
    price: 44900,
    mrp: 48900,
    stock: 15,
    low_stock_threshold: 3,
    brand: "Aashirvaad",
    tags: "No Maida",
    weight_grams: 10000,
    active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "p-5",
    shop_id: "default",
    category_id: "cat-1",
    subcategory_id: "sub-1-1",
    name: "Pillsbury Chakki Fresh Atta",
    image: img("Pillsbury", "2980b9"),
    type: "piece",
    unit_type: "pack",
    price: 21000,
    mrp: 23000,
    stock: 3,
    low_stock_threshold: 5,
    brand: "Pillsbury",
    tags: "Only 2 left",
    weight_grams: 5000,
    active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  // Rice
  {
    id: "p-6",
    shop_id: "default",
    category_id: "cat-1",
    subcategory_id: "sub-1-2",
    name: "India Gate Basmati Rice Classic",
    image: img("India Gate", "8e44ad"),
    type: "piece",
    unit_type: "pack",
    price: 18500,
    mrp: 21000,
    stock: 20,
    low_stock_threshold: 5,
    brand: "India Gate",
    tags: "Popular",
    weight_grams: 1000,
    active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "p-7",
    shop_id: "default",
    category_id: "cat-1",
    subcategory_id: "sub-1-2",
    name: "Daawat Rozana Gold Basmati Rice",
    image: img("Daawat", "16a085"),
    type: "piece",
    unit_type: "pack",
    price: 9500,
    mrp: 11000,
    stock: 30,
    low_stock_threshold: 5,
    brand: "Daawat",
    tags: "",
    weight_grams: 1000,
    active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  // Dal
  {
    id: "p-8",
    shop_id: "default",
    category_id: "cat-1",
    subcategory_id: "sub-1-3",
    name: "Tata Sampann Unpolished Toor Dal",
    image: img("Tata", "e67e22"),
    type: "piece",
    unit_type: "pack",
    price: 14500,
    mrp: 16000,
    stock: 18,
    low_stock_threshold: 5,
    brand: "Tata Sampann",
    tags: "",
    weight_grams: 1000,
    active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "p-9",
    shop_id: "default",
    category_id: "cat-1",
    subcategory_id: "sub-1-3",
    name: "Organic Tattva Masoor Dal",
    image: img("Organic", "27ae60"),
    type: "piece",
    unit_type: "pack",
    price: 16500,
    mrp: 18500,
    stock: 10,
    low_stock_threshold: 5,
    brand: "Organic Tattva",
    tags: "Organic",
    weight_grams: 1000,
    active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  // Dairy
  {
    id: "p-10",
    shop_id: "default",
    category_id: "cat-2",
    subcategory_id: "sub-2-1",
    name: "Amul Taaza Toned Milk 1L",
    image: img("Amul", "2980b9"),
    type: "piece",
    unit_type: "pack",
    price: 6800,
    mrp: 7200,
    stock: 50,
    low_stock_threshold: 10,
    brand: "Amul",
    tags: "Bought Earlier",
    active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "p-11",
    shop_id: "default",
    category_id: "cat-2",
    subcategory_id: "sub-2-2",
    name: "Amul Fresh Curd 400g",
    image: img("Amul", "2980b9"),
    type: "piece",
    unit_type: "pack",
    price: 4500,
    mrp: 5000,
    stock: 35,
    low_stock_threshold: 10,
    brand: "Amul",
    tags: "",
    active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "p-12",
    shop_id: "default",
    category_id: "cat-2",
    subcategory_id: "sub-2-3",
    name: "Amul Fresh Paneer 200g",
    image: img("Amul", "2980b9"),
    type: "piece",
    unit_type: "pack",
    price: 8500,
    mrp: 9500,
    stock: 15,
    low_stock_threshold: 5,
    brand: "Amul",
    tags: "",
    active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "p-13",
    shop_id: "default",
    category_id: "cat-2",
    subcategory_id: "sub-2-5",
    name: "Farm Fresh Eggs (6 pcs)",
    image: img("Eggs", "f1c40f"),
    type: "piece",
    unit_type: "pack",
    price: 4200,
    mrp: 4800,
    stock: 40,
    low_stock_threshold: 10,
    brand: "Farm Fresh",
    tags: "",
    active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  // Snacks
  {
    id: "p-14",
    shop_id: "default",
    category_id: "cat-3",
    subcategory_id: "sub-3-1",
    name: "Lay's Classic Salted Chips",
    image: img("Lays", "e74c3c"),
    type: "piece",
    unit_type: "pack",
    price: 3500,
    mrp: 4000,
    stock: 60,
    low_stock_threshold: 10,
    brand: "Lay's",
    tags: "Popular",
    active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "p-15",
    shop_id: "default",
    category_id: "cat-3",
    subcategory_id: "sub-3-2",
    name: "Haldiram's Bhujia Sev",
    image: img("Haldiram", "d35400"),
    type: "piece",
    unit_type: "pack",
    price: 5500,
    mrp: 6500,
    stock: 25,
    low_stock_threshold: 5,
    brand: "Haldiram's",
    tags: "",
    active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "p-16",
    shop_id: "default",
    category_id: "cat-3",
    subcategory_id: "sub-3-4",
    name: "Cadbury Dairy Milk Silk",
    image: img("Cadbury", "8e44ad"),
    type: "piece",
    unit_type: "pack",
    price: 8500,
    mrp: 9500,
    stock: 45,
    low_stock_threshold: 10,
    brand: "Cadbury",
    tags: "",
    active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  // Vegetables
  {
    id: "p-17",
    shop_id: "default",
    category_id: "cat-4",
    subcategory_id: "sub-4-1",
    name: "Fresh Tomatoes",
    image: img("Tomato", "e74c3c"),
    type: "weight",
    unit_type: "kg",
    price: 4000,
    mrp: 5000,
    stock: 50,
    low_stock_threshold: 10,
    brand: "Fresh",
    tags: "",
    weight_grams: 1000,
    active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "p-18",
    shop_id: "default",
    category_id: "cat-4",
    subcategory_id: "sub-4-1",
    name: "Fresh Onions",
    image: img("Onion", "9b59b6"),
    type: "weight",
    unit_type: "kg",
    price: 3500,
    mrp: 4500,
    stock: 80,
    low_stock_threshold: 10,
    brand: "Fresh",
    tags: "",
    weight_grams: 1000,
    active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "p-19",
    shop_id: "default",
    category_id: "cat-4",
    subcategory_id: "sub-4-2",
    name: "Bananas (Robusta)",
    image: img("Banana", "f1c40f"),
    type: "weight",
    unit_type: "kg",
    price: 6000,
    mrp: 7000,
    stock: 30,
    low_stock_threshold: 5,
    brand: "Fresh",
    tags: "",
    weight_grams: 1000,
    active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  // Beverages
  {
    id: "p-20",
    shop_id: "default",
    category_id: "cat-5",
    subcategory_id: "sub-5-1",
    name: "Tata Tea Premium",
    image: img("Tata Tea", "c0392b"),
    type: "piece",
    unit_type: "pack",
    price: 9500,
    mrp: 10500,
    stock: 40,
    low_stock_threshold: 10,
    brand: "Tata",
    tags: "",
    weight_grams: 500,
    active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  {
    id: "p-21",
    shop_id: "default",
    category_id: "cat-5",
    subcategory_id: "sub-5-2",
    name: "Coca-Cola 2L",
    image: img("Coke", "e74c3c"),
    type: "piece",
    unit_type: "piece",
    price: 8500,
    mrp: 9500,
    stock: 25,
    low_stock_threshold: 5,
    brand: "Coca-Cola",
    tags: "",
    active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  // Biscuits
  {
    id: "p-22",
    shop_id: "default",
    category_id: "cat-6",
    subcategory_id: "sub-3-3",
    name: "Parle-G Gold Biscuits",
    image: img("Parle-G", "f39c12"),
    type: "piece",
    unit_type: "pack",
    price: 1200,
    mrp: 1500,
    stock: 100,
    low_stock_threshold: 20,
    brand: "Parle",
    tags: "",
    weight_grams: 200,
    active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  // Personal Care
  {
    id: "p-23",
    shop_id: "default",
    category_id: "cat-7",
    subcategory_id: "",
    name: "Dove Cream Beauty Soap",
    image: img("Dove", "e91e63"),
    type: "piece",
    unit_type: "piece",
    price: 4500,
    mrp: 5200,
    stock: 30,
    low_stock_threshold: 10,
    brand: "Dove",
    tags: "",
    active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
  // Household
  {
    id: "p-24",
    shop_id: "default",
    category_id: "cat-8",
    subcategory_id: "",
    name: "Surf Excel Matic Liquid 1L",
    image: img("Surf", "3498db"),
    type: "piece",
    unit_type: "pack",
    price: 21000,
    mrp: 23500,
    stock: 15,
    low_stock_threshold: 5,
    brand: "Surf Excel",
    tags: "",
    active: true,
    created_at: "2024-01-01T00:00:00Z",
    updated_at: "2024-01-01T00:00:00Z",
  },
];

export const MOCK_FREQUENTLY_BOUGHT: FrequentlyBoughtBundle[] = [
  {
    id: "fb-1",
    name: "Favourites",
    images: [img("A", "e74c3c"), img("B", "3498db"), img("C", "f1c40f")],
    product_count: 12,
    category_id: "",
  },
  {
    id: "fb-2",
    name: "Chips & Namkeen",
    images: [img("Lays", "e74c3c"), img("Haldiram", "d35400")],
    product_count: 24,
    category_id: "cat-3",
  },
  {
    id: "fb-3",
    name: "Milk, Curd & Paneer",
    images: [img("Milk", "2980b9"), img("Curd", "f4d03f")],
    product_count: 18,
    category_id: "cat-2",
  },
  {
    id: "fb-4",
    name: "Chocolates & Candies",
    images: [img("Cadbury", "8e44ad"), img("Nestle", "e91e63")],
    product_count: 15,
    category_id: "cat-3",
  },
  {
    id: "fb-5",
    name: "Cakes & Biscuits",
    images: [img("Parle", "f39c12"), img("Britannia", "e67e22")],
    product_count: 20,
    category_id: "cat-6",
  },
  {
    id: "fb-6",
    name: "Vegetables & Fruits",
    images: [img("Veg", "2ecc71"), img("Fruit", "f1c40f")],
    product_count: 30,
    category_id: "cat-4",
  },
];

export function getMockCategories(): Category[] {
  return MOCK_CATEGORIES.map((c) => ({
    ...c,
    subcategories: MOCK_SUBCATEGORIES.filter((s) => s.category_id === c.id),
  }));
}

export function getMockProducts(): Product[] {
  const categories = getMockCategories();
  return MOCK_PRODUCTS.map((p) => ({
    ...p,
    category: categories.find((c) => c.id === p.category_id),
    subcategory: MOCK_SUBCATEGORIES.find((s) => s.id === p.subcategory_id),
  }));
}

export function getProductsByCategory(categoryId: string): Product[] {
  return getMockProducts().filter((p) => p.category_id === categoryId);
}

export function getProductsBySubcategory(subcategoryId: string): Product[] {
  return getMockProducts().filter((p) => p.subcategory_id === subcategoryId);
}

export function getFrequentlyBought(): FrequentlyBoughtBundle[] {
  return MOCK_FREQUENTLY_BOUGHT;
}
